==  Introduction

The goal of this workshop is to introduce simple circuits.  Students work with a set of basic components such as batteries, wires and LEDs.  Each of the projects is easy-to-do, fun and rewarding for students who can explore various methods of lighting LEDs.

=== Project Set

LED Throwies:: 
   A coin-cell battery lights an LED.  Add a magnet and tape them together to make a throwie that will stick to a metal surface. 
Squishy Circuits:: 
   Creating play dough with salt makes it a good conductor.  Making another batch with sugar instead of salt makes it an insulator.   Now, use the play dough to build simple circuits, lighting one or more LEDs.
LED Pop-up Cards::
   A creative pop-up card can have a hidden LED that works with conductive metal tape. 

=== Duration

LED Throwies is a very short introductory project that can be done a matter of minutes.  Yet, students can have more fun with it if given enough time to play and experiment.   The centerpiece of the workshop is Squishy Circuits, which can be done in a half-hour but also extended for many hours, given different components.   LED Pop-up Cards can be completed in a half-hour or so, given advance preparation.   

=== Participation

Because the basic components for these projects are inexpensive, and reusable, it is easy to do these projects with larger numbers of participants, and each one can have their own set of materials.   The projects in this workshop are good for students of almost any age, if they have not had previous experience building circuits.

=== Environment or space

These are tabletop projects that can be adapted to almost any environment.

=== Materials and Tools

These three projects use the same basic electronic components, which are inexpensive.  

=== Prerequisites 

There is no prerequisite for these projects, although playing with circuit blocks might be a good companion project, either before or after these projects. 

=== Level - 0

Workshop Facilitation

. None of these projects require students to have written instructions while doing the projects.
. You might have everyone do an LED throwie as a starter project.   Then allow small groups to choose either the LED pop-up card or the Squishy Circuits project.   If there’s time, allow these groups to switch projects.  




LED Pop-Up Card on Make:Projects
Videos
none exist.
Resources
Enchanted Learning has more information about the craft of pop-up cards.
Materials Organization and Preparation
1. Each student requires an LED and several strips of conductive tape. 
2. A roll of copper or metal tape is required for the LED pop-up card.
3. Templates can be prepared for tracing of figures or designs that can be incorporated into the card.   Examples: trees, fish, etc.
4. Have students build the basic pop-up card before adding the LED circuitry.  
5. The adhesive on the bottom of the copper tape could potentially cause the circuit to not work at all. It is working as an insulator and not a conductor.
6. The circuit can be more difficult to build because it has more points of possible contact.  Students need to keep the positive lead from touching the negative lead, or the tape that connects them to the battery.
Tools 
No special tools other than scissors are required. 
Facilitation Tips
1. It’s good to have a set of sample cards to use as models.  Make one for each group of students.
2. Make sure the edges of the metal tape do not overlap.  
3. Have students share their cards with each other at the end of the workshop.
3. Concepts and Skills Introduced
(incorporate more from Joel’s document but maybe link to a separate document with Joel explaining electricity.)
Concepts
1. The components of a simple circuit.
2. Batteries and LEDs have a positive and negative polarity. 
3. Different materials have different conductive and insulating properties.
Related Exercises
1. Ask students to draw a simple circuit on paper referencing the components they used in this workshop.